#Messages
commands: >
  My commands:
  /resources - Raiden Network resources
  /videos - Raiden Network related videos
  /conferences - Upcoming events
  /uraiden - MicroRaiden resources
  /extras - Extra commands

extras: >
  /previousevents - previous events of 2018
  /pulse - The Raiden Pulse series
  /community - Community contributions
  /tokenmodel - The Raiden Network Token Model
  /brainbot - Brainbot website and jobs
  /nightly - Nightly releases
  /releases - Github releases page
  /email - Raiden contact email
  /rules - RNC telegram channel rules
  /whenmoon - When?
  /disclaimer - RNC telegram channel disclaimer
  /rapps - A list of some apps implementing Raiden

resources: >
  Raiden Network resources:
  Website <https://raiden.network/>
  FAQ <https://raiden.network/faq.html>
  Github <https://github.com/raiden-network/>
  Dev Chat <https://gitter.im/raiden-network/raiden>
  Raiden Explorer <https://explorer.raiden.network/> (Kovan <https://kovan.explorer.raiden.network>, Ropsten <https://ropsten.explorer.raiden.network>, Rinkeby <https://rinkeby.explorer.raiden.network>)
  Raiden Network Roadmap <https://raiden.network/roadmap.html>
  Documentation <https://readthedocs.org/projects/raiden-network/>
  Specification PDF <https://media.readthedocs.org/pdf/raiden-network-specification/latest/raiden-network-specification.pdf>
  Medium Publications <https://medium.com/@raiden_network) and [Blog](https://medium.com/raiden-network>
  Twitter <https://twitter.com/raiden_network>
  Reddit <https://www.reddit.com/r/raidennetwork>
  Weekly Reddit Github Update <https://reddit.com/user/bor4/posts/>
  Workshops <http://workshop.raiden.network?

community: >
  Raideneer highlights:
  Raiden: Ethereum's Payment Channel Network <https://medium.com/@surferfc/raiden-ethereums-payment-channel-network-acc6e5c709b0> - Surferfc
  TopRDNtransfers telegram channel <https://t.me/TopRDNtransfers> - Kaleaso (Tim)
  Meeting Raiden @ Web3Summit <http://reddit.com/r/raidennetwork/comments/9red2i/meeting_raiden_web3summit/> - Surferfc
  This bot! <https://github.com/mat7ias/RNCbotDiscord>
  Non-profit 3D printed Raiden souvenir <https://www.shapeways.com/shops/raiden>
  The Devcon4 workshop on Windows <https://youtu.be/GBidfC7eOYI>
  Github Visualization <https://youtu.be/xqxTGF--Bhk>

conferences: >
  Upcoming Events:
  February 4th - CryptoMonday | Raiden - 2nd Layer Scaling on Ethereum <https://www.meetup.com/CryptoMonday-Bitcoin-Cologne/events/jmwnpqyzdbgb/>
  March 5th-7th - Ethereum Community Conference <https://ethcc.io/>
  March 12th - Mainz Crypto Community <https://www.meetup.com/Mainz-Crypto-Community/events/257370759/>

previousevents: >
  Recent Events:
  January 31st - GoeliCon <https://www.meetup.com/Department-of-Decentralization/events/258091601/>
  7/12-9/12 - Sponsoring <https://twitter.com/neutral_project/status/1064436809600397312> at ETHSingapore <https://ethsingapore.co/>
  9/11 - Raiden Workshop: lightning payment solution for Ethereum with its creators <https://eventbrite.es/e/entradas-raiden-workshop-lightning-payment-solution-for-ethereum-with-its-creators-52005322319>
  8/11 - Discover Raiden, a lightning payment solution for Ethereum <https://meetup.com/Devcentralised-Developing-DApps-Barcelona/events/255964749/>
  31/10-2/11 - Devcon4 <https://devcon4.ethereum.org/>
  29/10 - The Future of LAYER 2: Prague Edition <https://www.eventbrite.com/e/the-future-of-layer-2-prague-edition-tickets-51535876193>
  1/10-31/10 - Hacktoberfest <https://github.com/raiden-network/raiden/labels/hacktoberfest>
  5/9 - Full Node: Mass adApption & use-cases <https://eventbrite.com/e/mass-adapption-use-cases-golem-raiden-status-tickets-49559434603>
  7/9-9/9 - ETHBerlin Scaling & Interoperability Panel <https://ethberlin.com/>
  28/8 - Copenhagen Ethereum Meetup <https://twitter.com/raiden_network/status/1030051960949551109>
  19/7-20/7 - DappCon Lefteris and Augusto <https://dappcon.io/#speakers>
  30/6-1/7 - Off The Chain Workshop in Berlin <https://binarydistrict.com/courses/master-workshop-off-the-chain/>
  18/5 - State Channel Panel for Boston layer 2 scaling <https://workshopbostonblockchaincommunity.com/>

videos: >
  Raiden Network videos/presentations:
  Raiden youtube channel <https://youtube.com/channel/UCoUP_hnjUddEvbxmtNCcApg>
  Brainbot Technologies channel <https://youtube.com/channel/UCAfSoSy9FK5UqlSxqcsQElA/videos>
  Devcon1 <https://youtu.be/h791zjvf3uQ> - Heiko
  Devcon2 <https://youtu.be/4igFqFqQga4> - Heiko
  Berlin Ethereum 2016 <https://youtu.be/JuVP4iDVkoQ> - Lefteris
  Oktahedron podcast <https://oktahedron.diskordia.org/?podcast=oh007-raiden#t=1:56.687> - Augusto
  Devcon3 <https://youtu.be/00RPE96LRVM> - Lefteris
  Asseth <https://youtu.be/93qOwUSj4PQ> - Lefteris
  Edcon 2018 <https://youtu.be/VsZuDJMmVPY?t=7h45m51s> - Lefteris
  L2 Summit State Channel Panel <https://youtu.be/jzoS0tPUAiQ?t=2h10m9s> - Lefteris
  Off The Chain presentation <https://youtu.be/8Duil4pLzhI> - Lefteris
  DAPPCON 2018 <https://youtu.be/hSMIpl6e_Ow> - Lefteris
  DAPPCON 2018 Panel Talking State Channels and Plasma <https://youtu.be/zmS0i3ZQZak> - Lefteris
  Ethereum Asia Tour <https://youtu.be/MI5vgqq1hzA> - Jacob
  Copenhagen Ethereum Meetup <https://youtu.be/arecj2vyjlE> - Jacob
  Tackling Scalability Panel <https://youtu.be/AH2g-KpPk7w> - Lefteris
  Mass Adoption and Use-Cases <https://youtu.be/GrWqRVDOC4M> - Augusto
  ETHBerlin <https://view.ly/v/MrLm3vSB1XEK> - Lefteris
  Raiden Network Web Application Demo <https://youtu.be/ASWeFdHDK-E>
  The Future of Layer 2 - Prague Edition <https://youtu.be/htyJrK9VuCc> - Jacob
  Devcon4 2018 <https://youtu.be/v9UQlE2We50> - Lefteris
  Rock-Paper-Scissors on Raiden Network <https://youtu.be/Mv6Ukdu0Xso> - Loredana

uraiden: >
  MicroRaiden:
  uRaiden Github <https://micro.raiden.network/>
  uRaiden Codebase <https://github.com/raiden-network/microraiden>
  uRaiden Docs <https://microraiden.readthedocs.io/en/docs-develop/>
  uRaiden Dev Chat <https://gitter.im/raiden-network/microraiden>
  uRaiden Demo <https://demo.micro.raiden.network/>
  MicroRaiden videos:
  Presentation Devcon3 <https://youtu.be/yx0__aFvjzk?t=9m35s> - Loredana
  Berlin Meetup drone demo <https://youtube.com/watch?v=E6CIgJPxgpQ> - Loredana
  ScalingNOW! <https://youtu.be/81gK-5qLFeg> - Loredana

whenmoon: >
  The speed of light is 299.8km/s (or 299.792.458m/s). Average distance to the Moon is 384400km at the closest two points. 1.28 seconds on average for information traveling at the speed of light to reach the Moon.
  Although I think we can be more accurate about When Moon since the distance fluctuates between 363104-405704km. Which means that if we ignore computation/processing time the shortest time to the moon is 1.21 seconds ([time for light to reach the surface of the Moon from the Earth](https://i.imgur.com/nj8q3db.png)).
  For the longest time, we need to do a bit more and make some assumptions. First is that being the longest distance also implied that we have no direct line of sight and that we will need to send our Raiden Network transfer with the help of satellites. [OneWeb are setting up satellites with a low earth orbit of 1200km](https://en.wikipedia.org/wiki/OneWeb_satellite_constellation) so let's assume that's our satellite orbit for the Earth.
  For the Moon, we will also need to send the Raiden Network transfer to the furthest point and again need to use satellites. The lowest realistic lunar orbit is 15km (to avoid hitting lunar mountains, [which reach heights of 6.1km](https://en.wikipedia.org/wiki/Lunar_orbit)).
  So now we need to find the distance [for this path](https://i.imgur.com/a8VxSnm.png). With some quick maths, we can figure this distance out as such [this](https://i.imgur.com/1zNeIMt.png) and our final maximum distance being a total of 431538km. Again if we ignore computation/processing time between the Payee and Payer then we have a maximum transfer time of 1.44 seconds.
  I am happy to officially announce that Raiden Network can Moon in 1.21-1.44 seconds. Hope this helps!

rules: >
  Service Rules of Conduct:
  1) This channel is about freedom of speech, but please keep in mind that it has its limits. Passionate debate is welcome, but unreasonable disrespect to any fellow members of the group (and especially the Raiden team) will not be tolerated. Doing so may result in your message being removed (this will be discussed with you in private messages).
  2) Not allowed: referral links unrelated to Raiden, channel links, self promo media, pump and dump groups, NSFW content, excessive swearing, spam in general, doxxing.
  3) Excessive trolling will result in removed messages.
  4) Please stay on topic, this server is about the Raiden Network and scaling.

pulse: >
  Raiden [Pulse](https://medium.com/raiden-network):
  [Raiden Pulse #1: News from July and August](https://medium.com/raiden-network/raiden-pulse-1-news-from-july-and-august-423fae4e9d3e)
  [Raiden Pulse #2: News from September and October](https://medium.com/raiden-network/raiden-pulse-2-news-from-september-and-october-6a6c6be8ad67)
  [Raiden Pulse #3: News from November and December](https://medium.com/raiden-network/raiden-pulse-3-news-from-november-and-december-dd0da04961d3)

nightly: >
  [Raiden Network Nightlies Releases](https://raiden-nightlies.ams3.digitaloceanspaces.com/index.html)

releases: >
  [Raiden Network Releases List](https://github.com/raiden-network/raiden/releases)

email: >
  Raiden contact email: contact@raiden.network

brainbot: >
  [Brainbot](https://brainbot.li/)
  [Jobs](https://angel.co/brainbot-group/jobs)

tokenmodel: >
  [The Raiden Network Token Model](https://medium.com/@raiden_network/the-raiden-network-token-model-9b6ef8d0b64)

disclaimer: >
  This is an unofficial community consensus driven channel. Content within the Raiden Network Community (RNC) telegram channel may contain views and opinions, errors and omissions by which the content creator(s), member(s) and/or administrator(s) of RNC telegram group (and also this community bot) cannot be held liable. The wording and concepts regarding financial terminology are used for entertainment only and should never be considered investment advice.

rapps: >
  [Cryptogrannies](https://github.com/swops-io/ETHSingapore-project)
  [Raidenooh](https://github.com/pisuthd/raiden-dooh)
  [CryptoBotWars](https://cryptoplayer.one)

weeklyupdate: >
  Hey guys, [Weekly Update 51](https://www.reddit.com/r/raidennetwork/comments/ai8fpo/git_weekly_update_51/) is up! :)
  TL;DR
  Auxiliary services discussed into in more detail; a Pathfinding service (PFS) for routing payments is similarly comparable to a flight route application that we use anytime we need to make a flight with an intermediary airport (multihop). A Monitoring service (MS) will help ensure that @Mat7ias can't cheat @BOR44 out of tokens while he's offline.

mentions: >
  Some of the mentions of Raiden:
  GridPlus <https://drive.google.com/file/d/0Bz90riPGRHquNDVXVE81RmppaUk/view>
  RightMesh <https://www.rightmesh.io/docs/RightMeshTechnicalWhitepaper3.1.pdf>
  EthFinex <https://www.bitfinex.com/ethfinex-whitepaper.pdf>
  Bitwin <https://token.bitwin.com/files/Bitwin-Whitepaper.pdf>
  EnjinCoin <https://enjincoin.io/enjincoin_whitepaper.pdf>
  Golem <https://golem.network/crowdfunding/Golemwhitepaper.pdf>
  Gnosis <https://twitter.com/koeppelmann/status/931572694000324608>
  SmartMesh/SmartRaiden <https://smartmesh.io/>
  Exchange Union <https://github.com/ExchangeUnion/Docs/blob/master/XU-TechnicalPaper.md>
  Augur <https://medium.com/@AugurProject/augur-master-plan-42dda65a3e3d>
  Altcoin.io <Altcoin.io> Atomic Swap DEX
  Credit Protocol <https://blockmason.io/cp-whitepaper/Introduction-amp-Features/> Democratized credit
  Energy Web Foundation <http://energyweb.org/wp-content/uploads/2017/11/EWF_Test_Network_Public_PR_Nov_1_2017.pdf>
  Indahash <https://s3.eu-central-1.amazonaws.com/idh-files/ico-landing/indahash_whitepaper_ico.pdf>
  Kin <https://kin.kik.com/papers/Kin_Whitepaper_V1_English.pdf>
  OpenANX <https://www.openanx.org/en/assets/whitepaper/openANX_White_Paper_ENU.pdf> DEX platform
  PolySwarm <https://polyswarm.io/polyswarm-whitepaper.pdf> Threat intelligence
  Raidex <https://raidex.io/> L2 DEX
  Request <https://request.network/assets/pdf/request_whitepaper.pdf> Social marketplace
  Soma <https://soma.co/wp-content/uploads/2017/07/Soma-tech-Whitepaper.pdf>
  Trade <https://trade.io/whitepaper/EN.pdf> Trading platform
  Trustlines Network <https://github.com/trustlines-network/trustlines-network.github.io/blob/8f2d9aeff4d373eff6a8bba123a8e975bd52f104/documents/Projects/trustlines-network.github.io-master/_includes/platform.html>
  ULedger <https://uploads.strikinglycdn.com/files/2e0889ae-1cef-4c05-8486-6d077ad84c4d/ULD%20Key%20Tech%20Details%2011.4.17.pdf> IT Data and Storage
  Wala <http://wala-tokensale-website.s3-website-eu-west-1.amazonaws.com/dalawhitepaper.pdf>
  WALLETH <http://walleth.org/2017/11/28/thoughts-on-the-ux-of-payment-channels/> native Ethereum Android light client wallet
  WePower <https://wepower.network/WhitePaper-WePower.pdf> Green Energy
